deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
    - key: api.openshift.com/id
      operator: In
      values: ["2f1jfel0o7h687v2ellmepa1tbsgf7mq"] # TEMP Selector for POC (hs-mc-mps583as0)
    - key: api.openshift.com/environment
      operator: In
      values: ["staging"] # Also for POC Phase 2 target only staging (will remove later)
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values: ["management-cluster"]
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
