---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-operator-reinstall-sa
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-operator-reinstall-role
  namespace: openshift-monitoring
rules:
- apiGroups:
  - "operators.coreos.com"
  resources:
  - clusterserviceversions
  - subscriptions
  - installplans
  verbs:
  - list
  - get
  - delete
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-operator-reinstall-rb
  namespace: openshift-monitoring
roleRef:
  kind: Role
  name: sre-operator-reinstall-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sre-operator-reinstall-sa
  namespace: openshift-monitoring
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-operator-reinstall
  namespace: openshift-monitoring
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 300 # Kill the job pod if it runs for longer than 5 minutes
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: sre-operator-reinstall-sa
      containers:
      - name: sre-operator-reinstall
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        command:
            - sh
            - -c
            - |
              #!/bin/bash
              set -uxo pipefail
              NAMESPACE="openshift-monitoring"
              OPERATOR="configure-alertmanager-operator"

              # Export a clean version of the Subscription then delete it, if it exists
              recreate_subscription=true
              if oc get subscription.operators.coreos.com -n "$NAMESPACE" "$OPERATOR"; then
                oc get subscription.operators.coreos.com -n $NAMESPACE $OPERATOR -o json | jq 'del(.status) | del(.metadata.creationTimestamp) | del(.metadata.generation) | del(.metadata.resourceVersion) | del(.metadata.uid)' > /tmp/sub.json
                oc delete subscription.operators.coreos.com -n $NAMESPACE $OPERATOR
              else
                recreate_subscription=false
              fi

              # Delete all ClusterServiceVersions
              oc get clusterserviceversions.operators.coreos.com -n "$NAMESPACE" --no-headers | grep $OPERATOR | awk '{print $1}' | xargs oc delete clusterserviceversions.operators.coreos.com -n $NAMESPACE --wait=false

              # Delete all InstallPlans
              oc get installplans.operators.coreos.com -n "$NAMESPACE" --no-headers | grep $OPERATOR | awk '{print $1}' | xargs oc delete installplan.operators.coreos.com -n "$NAMESPACE"

              # Recreate the subscription that was exported earlier, if it exists
              if [ $recreate_subscription == "true" ]; then
                oc create -f /tmp/sub.json
              fi

              exit 0
