---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-operator-reinstall-sa
  namespace: <operator-namespace>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-operator-reinstall-role
  namespace: <operator-namespace>
rules:
- apiGroups:
  - "operators.coreos.com"
  resources:
  - clusterserviceversions
  - subscriptions
  - installplans
  verbs:
  - list
  - get
  - delete
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-operator-reinstall-rb
  namespace: <operator-namespace>
roleRef:
  kind: Role
  name: sre-operator-reinstall-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sre-operator-reinstall-sa
  namespace: <operator-namespace>
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-operator-reinstall
  namespace: openshift-monitoring
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 300 # Kill the job pod if it runs for longer than 5 minutes
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: sre-operator-reinstall-sa
      containers:
      - name: sre-operator-reinstall
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        command:
            - sh
            - -c
            - |
              #!/bin/bash
              set -uxo pipefail
              NAMESPACE="openshift-monitoring"
              OPERATOR="configure-alertmanager-operator"

              # Delete all ClusterServiceVersions
              oc get clusterserviceversions.operators.coreos.com -n "$NAMESPACE" --no-headers | grep $OPERATOR | awk '{print $1}' | xargs oc delete clusterserviceversions.operators.coreos.com -n $NAMESPACE --wait=false

              exit 0
