---
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-operator-reinstall
  namespace: openshift-route-monitor-operator
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sre-operator-reinstall
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        serviceAccount: sre-operator-reinstall-sa
        serviceAccountName: sre-operator-reinstall-sa
        command:
        - sh
        - -c
        - |
          #!/bin/bash
              set -euxo pipefail
              NAMESPACE=openshift-route-monitor-operator
              OPERATOR=route-monitor-operator

              # Look for a CSV, then perform the reinstall if found. If you want to _always_ reinstall, remove this check and just keep the logic inside the "if"
              CSV_FOUND=$(oc -n "$NAMESPACE" get clusterserviceversions.operators.coreos.com -o name | grep "$OPERATOR")
              if [[ ! -z "$CSV_FOUND" ]]; then
                # The OLM dance
                # delete all installplans (if found) (the true is so we don't fail set -e)
                installplans=$(oc get installplans.operators.coreos.com -n "$NAMESPACE" --no-headers | awk '{print $1}' | grep "$OPERATOR" || true | awk '{print $1}')
                if [[ -n "$installplans" ]]; then
                  echo "$installplans" | xargs oc delete installplan.operators.coreos.com -n "$NAMESPACE"
                fi
                # get subscription
                oc get subscription.operators.coreos.com -n $NAMESPACE $OPERATOR -o json | jq 'del(.status) | del(.metadata.creationTimestamp) | del(.metadata.generation) | del(.metadata.resourceVersion) | del(.metadata.uid)' > /tmp/sub.json
                # delete subscription
                oc delete subscription.operators.coreos.com -n $NAMESPACE $OPERATOR
                # create subscription using the following json
                oc create -f /tmp/sub.json
                # delete all CSVs
                oc get clusterserviceversions.operators.coreos.com -n $NAMESPACE | grep $OPERATOR | awk '{print $1}' | xargs oc delete clusterserviceversions.operators.coreos.com -n $NAMESPACE --wait=false
              fi
              exit 0
